// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: compiler_protos/compiler.proto

package compiler_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecuteRequest_Code
	//	*ExecuteRequest_Input
	Payload       isExecuteRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_compiler_protos_compiler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_protos_compiler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_compiler_protos_compiler_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecuteRequest) GetPayload() isExecuteRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecuteRequest) GetCode() *Code {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteRequest_Code); ok {
			return x.Code
		}
	}
	return nil
}

func (x *ExecuteRequest) GetInput() *Input {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteRequest_Input); ok {
			return x.Input
		}
	}
	return nil
}

type isExecuteRequest_Payload interface {
	isExecuteRequest_Payload()
}

type ExecuteRequest_Code struct {
	Code *Code `protobuf:"bytes,2,opt,name=code,proto3,oneof"`
}

type ExecuteRequest_Input struct {
	Input *Input `protobuf:"bytes,3,opt,name=input,proto3,oneof"`
}

func (*ExecuteRequest_Code) isExecuteRequest_Payload() {}

func (*ExecuteRequest_Input) isExecuteRequest_Payload() {}

type Code struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	SourceCode    string                 `protobuf:"bytes,2,opt,name=source_code,json=sourceCode,proto3" json:"source_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Code) Reset() {
	*x = Code{}
	mi := &file_compiler_protos_compiler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Code) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Code) ProtoMessage() {}

func (x *Code) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_protos_compiler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Code.ProtoReflect.Descriptor instead.
func (*Code) Descriptor() ([]byte, []int) {
	return file_compiler_protos_compiler_proto_rawDescGZIP(), []int{1}
}

func (x *Code) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Code) GetSourceCode() string {
	if x != nil {
		return x.SourceCode
	}
	return ""
}

type Input struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputText     string                 `protobuf:"bytes,1,opt,name=input_text,json=inputText,proto3" json:"input_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Input) Reset() {
	*x = Input{}
	mi := &file_compiler_protos_compiler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_protos_compiler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_compiler_protos_compiler_proto_rawDescGZIP(), []int{2}
}

func (x *Input) GetInputText() string {
	if x != nil {
		return x.InputText
	}
	return ""
}

type ExecuteResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecuteResponse_Output
	//	*ExecuteResponse_Error
	//	*ExecuteResponse_Status
	Payload       isExecuteResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_compiler_protos_compiler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_protos_compiler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_compiler_protos_compiler_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecuteResponse) GetPayload() isExecuteResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecuteResponse) GetOutput() *Output {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteResponse_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *ExecuteResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ExecuteResponse) GetStatus() *Status {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteResponse_Status); ok {
			return x.Status
		}
	}
	return nil
}

type isExecuteResponse_Payload interface {
	isExecuteResponse_Payload()
}

type ExecuteResponse_Output struct {
	Output *Output `protobuf:"bytes,2,opt,name=output,proto3,oneof"`
}

type ExecuteResponse_Error struct {
	Error *Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type ExecuteResponse_Status struct {
	Status *Status `protobuf:"bytes,4,opt,name=status,proto3,oneof"`
}

func (*ExecuteResponse_Output) isExecuteResponse_Payload() {}

func (*ExecuteResponse_Error) isExecuteResponse_Payload() {}

func (*ExecuteResponse_Status) isExecuteResponse_Payload() {}

type Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputText    string                 `protobuf:"bytes,1,opt,name=output_text,json=outputText,proto3" json:"output_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_compiler_protos_compiler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_protos_compiler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_compiler_protos_compiler_proto_rawDescGZIP(), []int{4}
}

func (x *Output) GetOutputText() string {
	if x != nil {
		return x.OutputText
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorText     string                 `protobuf:"bytes,1,opt,name=error_text,json=errorText,proto3" json:"error_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_compiler_protos_compiler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_protos_compiler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_compiler_protos_compiler_proto_rawDescGZIP(), []int{5}
}

func (x *Error) GetErrorText() string {
	if x != nil {
		return x.ErrorText
	}
	return ""
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_compiler_protos_compiler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_protos_compiler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_compiler_protos_compiler_proto_rawDescGZIP(), []int{6}
}

func (x *Status) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

var File_compiler_protos_compiler_proto protoreflect.FileDescriptor

const file_compiler_protos_compiler_proto_rawDesc = "" +
	"\n" +
	"\x1ecompiler_protos/compiler.proto\x12\bcompiler\"\x89\x01\n" +
	"\x0eExecuteRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12$\n" +
	"\x04code\x18\x02 \x01(\v2\x0e.compiler.CodeH\x00R\x04code\x12'\n" +
	"\x05input\x18\x03 \x01(\v2\x0f.compiler.InputH\x00R\x05inputB\t\n" +
	"\apayload\"C\n" +
	"\x04Code\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x1f\n" +
	"\vsource_code\x18\x02 \x01(\tR\n" +
	"sourceCode\"&\n" +
	"\x05Input\x12\x1d\n" +
	"\n" +
	"input_text\x18\x01 \x01(\tR\tinputText\"\xbc\x01\n" +
	"\x0fExecuteResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12*\n" +
	"\x06output\x18\x02 \x01(\v2\x10.compiler.OutputH\x00R\x06output\x12'\n" +
	"\x05error\x18\x03 \x01(\v2\x0f.compiler.ErrorH\x00R\x05error\x12*\n" +
	"\x06status\x18\x04 \x01(\v2\x10.compiler.StatusH\x00R\x06statusB\t\n" +
	"\apayload\")\n" +
	"\x06Output\x12\x1f\n" +
	"\voutput_text\x18\x01 \x01(\tR\n" +
	"outputText\"&\n" +
	"\x05Error\x12\x1d\n" +
	"\n" +
	"error_text\x18\x01 \x01(\tR\terrorText\"\x1e\n" +
	"\x06Status\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state2R\n" +
	"\fCodeExecutor\x12B\n" +
	"\aExecute\x12\x18.compiler.ExecuteRequest\x1a\x19.compiler.ExecuteResponse(\x010\x01B\x1cZ\x1agenprotos/compiler_serviceb\x06proto3"

var (
	file_compiler_protos_compiler_proto_rawDescOnce sync.Once
	file_compiler_protos_compiler_proto_rawDescData []byte
)

func file_compiler_protos_compiler_proto_rawDescGZIP() []byte {
	file_compiler_protos_compiler_proto_rawDescOnce.Do(func() {
		file_compiler_protos_compiler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_compiler_protos_compiler_proto_rawDesc), len(file_compiler_protos_compiler_proto_rawDesc)))
	})
	return file_compiler_protos_compiler_proto_rawDescData
}

var file_compiler_protos_compiler_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_compiler_protos_compiler_proto_goTypes = []any{
	(*ExecuteRequest)(nil),  // 0: compiler.ExecuteRequest
	(*Code)(nil),            // 1: compiler.Code
	(*Input)(nil),           // 2: compiler.Input
	(*ExecuteResponse)(nil), // 3: compiler.ExecuteResponse
	(*Output)(nil),          // 4: compiler.Output
	(*Error)(nil),           // 5: compiler.Error
	(*Status)(nil),          // 6: compiler.Status
}
var file_compiler_protos_compiler_proto_depIdxs = []int32{
	1, // 0: compiler.ExecuteRequest.code:type_name -> compiler.Code
	2, // 1: compiler.ExecuteRequest.input:type_name -> compiler.Input
	4, // 2: compiler.ExecuteResponse.output:type_name -> compiler.Output
	5, // 3: compiler.ExecuteResponse.error:type_name -> compiler.Error
	6, // 4: compiler.ExecuteResponse.status:type_name -> compiler.Status
	0, // 5: compiler.CodeExecutor.Execute:input_type -> compiler.ExecuteRequest
	3, // 6: compiler.CodeExecutor.Execute:output_type -> compiler.ExecuteResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_compiler_protos_compiler_proto_init() }
func file_compiler_protos_compiler_proto_init() {
	if File_compiler_protos_compiler_proto != nil {
		return
	}
	file_compiler_protos_compiler_proto_msgTypes[0].OneofWrappers = []any{
		(*ExecuteRequest_Code)(nil),
		(*ExecuteRequest_Input)(nil),
	}
	file_compiler_protos_compiler_proto_msgTypes[3].OneofWrappers = []any{
		(*ExecuteResponse_Output)(nil),
		(*ExecuteResponse_Error)(nil),
		(*ExecuteResponse_Status)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_compiler_protos_compiler_proto_rawDesc), len(file_compiler_protos_compiler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_compiler_protos_compiler_proto_goTypes,
		DependencyIndexes: file_compiler_protos_compiler_proto_depIdxs,
		MessageInfos:      file_compiler_protos_compiler_proto_msgTypes,
	}.Build()
	File_compiler_protos_compiler_proto = out.File
	file_compiler_protos_compiler_proto_goTypes = nil
	file_compiler_protos_compiler_proto_depIdxs = nil
}
